defaults:
  local: ../hpack.yaml

name: merge-bot-core
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- bytestring
- exceptions
- github-rest
- github-schemas
- graphql-client
- http-client
- http-types
- monad-loops
- text
- time
- transformers
- unordered-containers
- yaml

library:
  source-dirs: src
