defaults:
  local: ../hpack.yaml

name: merge-bot-core
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- bytestring
- github-rest
- github-schemas
- graphql-client
- http-client
- http-types
- monad-logger
- text
- time
- transformers
- unliftio
- unliftio-core
- unordered-containers
- yaml

library:
  source-dirs: src

tests:
  merge-bot-core-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - aeson-qq
      - merge-bot-core
      - tasty
      - tasty-quickcheck
