defaults:
  local: ../hpack.yaml

name: merge-bot-core
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- exceptions
- github-rest
- graphql-client
- text
- transformers

library:
  source-dirs: src
