resolver: lts-13.5

packages:
  - aeson-schemas
  - github-rest
  - graphql
  - graphql/example
  - merge-bot
  - merge-bot-core
  - servant-github-app
  - template-haskell-test-utils

extra-deps:
  - jwt-0.9.0
