resolver: lts-13.5

packages:
  - github-schemas
  - graphql
  - graphql/example
  - merge-bot
  - merge-bot-core
  - servant-github-app

extra-deps:
  - aeson-schemas-1.0.2
  - github: LeapYear/github-rest
    commit: 6ac0c04659e4431dae33ffdda32a3fb9db17f779
  - jwt-0.9.0
  - th-test-utils-1.0.0
