resolver: lts-13.5

packages:
  - github-rest
  - github-schemas
  - graphql
  - graphql/example
  - merge-bot
  - merge-bot-core
  - servant-github-app

extra-deps:
  - aeson-schemas-1.0.2
  - jwt-0.9.0
  - th-test-utils-1.0.0
