resolver: lts-16.9

packages:
  - github-schemas
  - merge-bot
  - merge-bot-core
  - servant-github-app

extra-deps:
  - aeson-schemas-1.2.0
  - github: LeapYear/github-rest
    commit: 0f90f10eeede4697f0faba569734f87fdc07c61a
  - github: LeapYear/graphql-client
    commit: 26689f995878a861e79c0f5554870ebf1ce70d95
    subdirs:
      - graphql-client
