defaults:
  local: ../../hpack.yaml

name: graphql-example
version: 0.1.0

dependencies:
  - aeson
  - base
  - graphql-client
  - text

library:
  source-dirs: src

executable:
  source-dirs:    exe
  main:           Main.hs
  dependencies:
    - graphql-example

tests:
  graphql-example-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - aeson-qq
      - bytestring
      - graphql-example
      - tasty
      - tasty-golden
