defaults:
  local: ../hpack.yaml

name: template-haskell-test-utils
version: 0.1.0

dependencies:
- base
- template-haskell
- transformers

library:
  source-dirs: src

tests:
  template-haskell-test-utils-test:
    source-dirs:  test
    main:         Main.hs
