version: 2.1

_aliases:
  - &only-mergit
    # https://ideas.circleci.com/cloud-feature-requests/p/dont-error-when-all-workflows-excluded
    filters:
      branches:
        only:
          - /staging-.*/
          - /trying-.*/

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_test:
          <<: *only-mergit
      - lint:
          <<: *only-mergit

jobs:
  build_and_test:
    executor: docker-ci
    steps:
      - init_ci_job
      - install_stack
      - with_stack_cache:
          steps:
            - run:
                name: Build third-party Haskell libraries
                command: stack build --test --only-dependencies -j1
      - run: stack build --test --no-run-tests
      # https://github.com/commercialhaskell/stack/issues/5024
      - run: stack test -j1
      - upload_artifacts

  lint:
    executor: docker-ci
    steps:
      - init_ci_job
      - run: sudo apt-get update
      - run:
          name: Install pre-commit
          command: |
            sudo apt-get install -y python3-distutils
            curl https://pre-commit.com/install-local.py | python3 -
            sudo ln -sf ~/bin/pre-commit /usr/local/bin/pre-commit
            pre-commit --version
      - install_stack
      - with_stack_cache:
          steps:
            - run: sudo apt-get install -y libtinfo-dev
            - run: stack build --fast -j1 hlint fourmolu
      - run:
          name: Lint via pre-commit
          command: pre-commit run --all-files -v --show-diff-on-failure

executors:
  docker-ci:
    docker:
      - image: cimg/base:2021.04

commands:
  init_ci_job:
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build cache key
          command: |
            FILES=(
              stack.yaml
              hpack.yaml
              github-schemas/package.yaml
              mergit/package.yaml
              mergit-core/package.yaml
              servant-github-app/package.yaml
            )
            cat "${FILES[@]}" > cache-key.txt
            curl -sSL https://get.haskellstack.org/ | sed -n 's/^STACK_VERSION="\(.*\)"/\1/p' >> cache-key.txt

  install_stack:
    steps:
      - run:
          name: Install stack
          command: |
            sudo apt-get update
            curl -sSL https://get.haskellstack.org/ | sh
            stack --version

  with_stack_cache:
    parameters:
      steps:
        type: steps
    steps:
      - restore_cache:
          keys:
            - v2-{{ checksum "cache-key.txt" }}-{{ .Environment.CIRCLE_JOB }}
            - v2-{{ checksum "cache-key.txt" }}
      - << parameters.steps >>
      - save_cache:
          key: v2-{{ checksum "cache-key.txt" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - ~/.stack

  upload_artifacts:
    steps:
      - run:
          name: Collect artifacts
          command: |
            mkdir -p artifacts/
            cp -v "$(stack exec -- bash -c 'type -P mergit')" artifacts/
      - store_artifacts:
          path: artifacts/
