version: 2.1

_aliases:
  - &only-mergit
    # https://ideas.circleci.com/cloud-feature-requests/p/dont-error-when-all-workflows-excluded
    filters:
      branches:
        only:
          - /staging-.*/
          - /trying-.*/
          - main

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_test:
          <<: *only-mergit
      - build_docker:
          context:
          - artifactory
          <<: *only-mergit
      - lint:
          context:
          - artifactory
          <<: *only-mergit
      - deploy:
          filters: { branches: { only: [main] } }
          requires:
            - build_docker
            - build_and_test

jobs:
  build_and_test:
    executor: docker-ci
    steps:
      - init_ci_job
      - install_stack
      - with_stack_cache:
          steps:
            - run:
                name: Build third-party Haskell libraries
                command: stack build --test --only-dependencies -j1
      - run: stack build --test --no-run-tests
      # https://github.com/commercialhaskell/stack/issues/5024
      - run: stack test -j1
      - upload_artifacts

  build_docker:
    executor: machine-ubuntu
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t mergit .
      - run:
          name: Save Docker image
          command: docker save mergit | gzip > mergit-docker.tar.gz
      - store_artifacts:
          path: mergit-docker.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - mergit-docker.tar.gz

  lint:
    executor: docker-ci
    steps:
      - init_ci_job
      - run: sudo apt-get update
      - run:
          name: Install pre-commit
          command: |
            sudo apt-get install -y python3-distutils
            curl https://pre-commit.com/install-local.py | python3 -
            sudo ln -sf ~/bin/pre-commit /usr/local/bin/pre-commit
            pre-commit --version
      - install_stack
      - with_stack_cache:
          steps:
            - run: sudo apt-get install -y libtinfo-dev
            - run: stack build --fast -j1 hlint fourmolu
      - run:
          name: Lint via pre-commit
          command: pre-commit run --all-files -v --show-diff-on-failure

  deploy:
    executor: machine-ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Login to Dockerhub
          command: docker login -u leapyear1 --password-stdin \<<< "${DOCKERHUB_TOKEN}"
      - run:
          name: Load Docker image
          command: docker load -i mergit-docker.tar.gz
      - run:
          name: Tag + push Docker image
          command: |
            set -x
            for TAG in "latest" "$(date +%Y-%m-%d)" "${CIRCLE_SHA1}"; do
              docker tag mergit "leapyear1/mergit:${TAG}"
              docker push "leapyear1/mergit:${TAG}"
            done

executors:
  docker-ci:
    docker:
      - image: artifacts.leapyear.io/dockerhub-remote/cimg/base:2021.04
        auth:
          username: $ARTIFACTORY_USER
          password: $ARTIFACTORY_PASSWORD
  machine-ubuntu:
    machine: true

commands:
  init_ci_job:
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build cache key
          command: |
            FILES=(
              stack.yaml
              hpack.yaml
              github-schemas/package.yaml
              mergit/package.yaml
              mergit-core/package.yaml
              servant-github-app/package.yaml
            )
            cat "${FILES[@]}" > cache-key.txt
            curl -sSL https://get.haskellstack.org/ | sed -n 's/^STACK_VERSION="\(.*\)"/\1/p' >> cache-key.txt

  install_stack:
    steps:
      - run:
          name: Install stack
          command: |
            sudo apt-get update
            curl -sSL https://get.haskellstack.org/ | sh
            stack --version

  with_stack_cache:
    parameters:
      steps:
        type: steps
    steps:
      - restore_cache:
          keys:
            - v2-{{ checksum "cache-key.txt" }}-{{ .Environment.CIRCLE_JOB }}
            - v2-{{ checksum "cache-key.txt" }}
      - << parameters.steps >>
      - save_cache:
          key: v2-{{ checksum "cache-key.txt" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - ~/.stack

  upload_artifacts:
    steps:
      - run:
          name: Collect artifacts
          command: |
            mkdir -p artifacts/
            cp -v "$(stack exec -- bash -c 'type -P mergit')" artifacts/
      - store_artifacts:
          path: artifacts/
