defaults:
  local: ../hpack.yaml

name: merge-bot
version: 0.1.0

dependencies:
- aeson
- base
- bytestring
- case-insensitive
- cryptonite
- jose
- lens
- merge-bot-core
- mtl
- text
- time
- wai
- x509
- x509-store

library:
  source-dirs: src

executables:
  merge-bot:
    source-dirs:  exe
    main:         Main.hs
    dependencies:
    - merge-bot
    - warp
