defaults:
  local: ../hpack.yaml

name: servant-github-app
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- bytestring
- case-insensitive
- containers
- cryptonite
- github-rest
- github-schemas
- http-types
- jwt
- memory
- servant-server
- text
- wai

library:
  source-dirs: src

executables:
  servant-github-app-example:
    source-dirs: exe
    main: Main.hs
    dependencies:
    - servant-github-app
    - warp

tests:
  servant-github-app-test:
    source-dirs: test
    main: Main.hs
    dependencies:
    - aeson
    - aeson-qq
    - bytestring
    - http-types
    - jwt
    - servant-github-app
    - tasty
    - tasty-hunit
    - text
    - wai
    - wai-extra
