defaults:
  local: ../hpack.yaml

name: servant-github-app
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- bytestring
- case-insensitive
- containers
- cryptonite
- github-rest
- http-types
- jwt
- memory
- servant-server
- text
- time
- wai

library:
  source-dirs: src

executables:
  servant-github-app-example:
    source-dirs: exe
    main: Main.hs
    dependencies:
    - servant-github-app
    - warp
