defaults:
  local: ../hpack.yaml

name: github-rest
version: 0.1.0

dependencies:
- aeson
- base
- bytestring
- http-client
- http-client-tls
- http-types
- jwt
- mtl
- scientific
- text
- time
- transformers
- unliftio
- unliftio-core

library:
  source-dirs: src
