defaults:
  local: ../hpack.yaml

name: github-rest
version: 0.1.0

dependencies:
- aeson
- base
- bytestring
- exceptions
- http-client
- http-client-tls
- http-types
- jwt
- mtl
- scientific
- text
- time

library:
  source-dirs: src
