defaults:
  local: ../hpack.yaml

name: merge-bot-core
version: 0.1.0

dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - exceptions
  - graphql-client
  - http-client
  - http-client-tls
  - http-types
  - iso8601-time
  - mtl
  - text
  - time
  - transformers

library:
  source-dirs: src
