defaults:
  local: ../hpack.yaml

name: merge-bot-core
version: 0.1.0

dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - exceptions
  - extra
  - github-rest
  - graphql-client
  - http-client
  - http-types
  - mtl
  - text
  - time
  - transformers
  - yaml

library:
  source-dirs: src

tests:
  merge-bot-core-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - aeson
      - aeson-qq
      - bytestring
      - merge-bot-core
      - QuickCheck
      - tasty
      - tasty-golden
      - tasty-quickcheck
