defaults:
  local: ../hpack.yaml

name: merge-bot-core
version: 0.1.0

dependencies:
  - aeson
  - base
  - containers
  - graphql-client
  - iso8601-time
  - text
  - time

library:
  source-dirs: src
