defaults:
  local: ../hpack.yaml

name: merge-bot-server
version: 0.1.0

dependencies:
- aeson
- base
- exceptions
- graphql-client
- merge-bot-core
- monad-control
- mtl
- servant-server
- transformers
- transformers-base

library:
  source-dirs: src

executables:
  merge-bot:
    source-dirs:  exe
    main:         Main.hs
    dependencies:
    - merge-bot-server
    - warp
