defaults:
  local: ../hpack.yaml

name: graphql-client
version: 0.1.0

dependencies:
  - aeson
  - base
  - megaparsec
  - path
  - path-io
  - scientific
  - template-haskell
  - text
  - th-utilities
  - unordered-containers
  - vector

library:
  source-dirs: src
