defaults:
  local: ../hpack.yaml

name: graphql-client
version: 0.1.0

dependencies:
  - aeson
  - base
  - path
  - path-io
  - template-haskell
  - text
  - unordered-containers

library:
  source-dirs: src
