defaults:
  local: ../hpack.yaml

name: graphql-client
version: 0.1.0

dependencies:
  - aeson
  - aeson-schemas
  - base
  - bytestring
  - http-client
  - http-client-tls
  - http-types
  - mtl
  - path
  - path-io
  - scientific
  - template-haskell
  - text
  - transformers
  - unliftio-core
  - unordered-containers

library:
  source-dirs: src
