defaults:
  local: ../hpack.yaml

name: merge-bot
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- blaze-html
- bytestring
- data-default
- github-rest
- github-schemas
- graphql-client
- http-client
- http-types
- jose
- merge-bot-core
- monad-logger
- mtl
- req
- servant-auth-server
- servant-blaze
- servant-github-app
- servant-server
- text
- unliftio
- warp
- x509
- x509-store

library:
  source-dirs: src

executable:
  source-dirs: exe
  main:        Main.hs
  dependencies:
    - merge-bot
