defaults:
  local: ../hpack.yaml

name: merge-bot
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- blaze-html
- bytestring
- containers
- cookie
- data-default
- github-rest
- github-schemas
- graphql-client
- http-api-data
- http-client
- http-client-tls
- http-types
- jose
- merge-bot-core
- monad-logger
- mtl
- servant-auth-server
- servant-blaze
- servant-github-app
- servant-server
- stm
- text
- unliftio
- unordered-containers
- wai
- warp
- x509
- x509-store

library:
  source-dirs: src

executable:
  source-dirs: exe
  main:        Main.hs
  dependencies:
    - merge-bot

tests:
  merge-bot-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - merge-bot
      - tasty
      - tasty-quickcheck
