defaults:
  local: ../hpack.yaml

name: merge-bot
version: 0.1.0

dependencies:
- aeson
- aeson-schemas
- base
- blaze-html
- bytestring
- github-rest
- github-schemas
- http-types
- merge-bot-core
- monad-logger
- servant-auth-server
- servant-blaze
- servant-github-app
- servant-server
- text
- unliftio
- warp

library:
  source-dirs: src

executable:
  source-dirs: exe
  main:        Main.hs
  dependencies:
    - merge-bot
