defaults:
  local: ../hpack.yaml

name: merge-bot
version: 0.1.0

dependencies:
- aeson-schemas
- async
- base
- github-rest
- github-schemas
- http-types
- merge-bot-core
- servant-github-app
- servant-server
- text
- warp

library:
  source-dirs: src

executable:
  source-dirs: exe
  main:        Main.hs
  dependencies:
    - merge-bot
